// Generated by gencpp from file sensors/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SENSORS_MESSAGE_ADDTWOINTS_H
#define SENSORS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <sensors/AddTwoIntsRequest.h>
#include <sensors/AddTwoIntsResponse.h>


namespace sensors
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace sensors


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensors::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::sensors::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::sensors::AddTwoInts > {
  static const char* value()
  {
    return "sensors/AddTwoInts";
  }

  static const char* value(const ::sensors::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::sensors::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::sensors::AddTwoInts > 
template<>
struct MD5Sum< ::sensors::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensors::AddTwoInts >::value();
  }
  static const char* value(const ::sensors::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensors::AddTwoIntsRequest> should match 
// service_traits::DataType< ::sensors::AddTwoInts > 
template<>
struct DataType< ::sensors::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sensors::AddTwoInts >::value();
  }
  static const char* value(const ::sensors::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensors::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::sensors::AddTwoInts > 
template<>
struct MD5Sum< ::sensors::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensors::AddTwoInts >::value();
  }
  static const char* value(const ::sensors::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensors::AddTwoIntsResponse> should match 
// service_traits::DataType< ::sensors::AddTwoInts > 
template<>
struct DataType< ::sensors::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sensors::AddTwoInts >::value();
  }
  static const char* value(const ::sensors::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSORS_MESSAGE_ADDTWOINTS_H
