// Generated by gencpp from file sensors/ListCameras.msg
// DO NOT EDIT!


#ifndef SENSORS_MESSAGE_LISTCAMERAS_H
#define SENSORS_MESSAGE_LISTCAMERAS_H

#include <ros/service_traits.h>


#include <sensors/ListCamerasRequest.h>
#include <sensors/ListCamerasResponse.h>


namespace sensors
{

struct ListCameras
{

typedef ListCamerasRequest Request;
typedef ListCamerasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListCameras
} // namespace sensors


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensors::ListCameras > {
  static const char* value()
  {
    return "855b31192ab61744e7deb992d94db7ff";
  }

  static const char* value(const ::sensors::ListCameras&) { return value(); }
};

template<>
struct DataType< ::sensors::ListCameras > {
  static const char* value()
  {
    return "sensors/ListCameras";
  }

  static const char* value(const ::sensors::ListCameras&) { return value(); }
};


// service_traits::MD5Sum< ::sensors::ListCamerasRequest> should match 
// service_traits::MD5Sum< ::sensors::ListCameras > 
template<>
struct MD5Sum< ::sensors::ListCamerasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensors::ListCameras >::value();
  }
  static const char* value(const ::sensors::ListCamerasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensors::ListCamerasRequest> should match 
// service_traits::DataType< ::sensors::ListCameras > 
template<>
struct DataType< ::sensors::ListCamerasRequest>
{
  static const char* value()
  {
    return DataType< ::sensors::ListCameras >::value();
  }
  static const char* value(const ::sensors::ListCamerasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensors::ListCamerasResponse> should match 
// service_traits::MD5Sum< ::sensors::ListCameras > 
template<>
struct MD5Sum< ::sensors::ListCamerasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensors::ListCameras >::value();
  }
  static const char* value(const ::sensors::ListCamerasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensors::ListCamerasResponse> should match 
// service_traits::DataType< ::sensors::ListCameras > 
template<>
struct DataType< ::sensors::ListCamerasResponse>
{
  static const char* value()
  {
    return DataType< ::sensors::ListCameras >::value();
  }
  static const char* value(const ::sensors::ListCamerasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSORS_MESSAGE_LISTCAMERAS_H
